# SPDX-FileCopyrightText: 2026 github.com/aburow
# SPDX-License-Identifier: GPL-3.0-only

"""CyberPower Modbus per-driver catalog.

ARCHITECTURAL MODEL:
====================

The catalog is a PER-DRIVER exposure schema that defines ALL exposable datapoints
for this driver family. It is NOT a global schema or runtime state.

Responsibilities:
-----------------
1. CATALOG: Declares all possible datapoints this driver can expose
   - Canonical keys (stable identity)
   - Source declarations (modbus register, SNMP OID, etc.)
   - Aliases (compatibility with legacy register/raw keys)
   - Metadata (labels, units, categories, tiers)
   - Tier model (normalized vs extended exposure)

2. PROFILE: Selects which catalog entries apply to a specific model/variant
   - Profile is a SUBSET/FILTER over catalog applicability
   - Profiles reference catalog entries by canonical key
   - Profiles add polling metadata (poll_group, word_order, etc.)

3. RUNTIME: Resolves selected catalog entries from declared sources
   - Runtime polls only what profile selected from catalog
   - Runtime uses catalog source declarations (register, OID)
   - Runtime merges via canonical keys, not raw/register keys

4. DISCOVERY: Publishes according to tier and configuration
   - Normalized tier: enabled by default
   - Extended tier: opt-in only (enable_extended_fields)
   - Catalog entry does NOT imply automatic publication

KEY PRINCIPLES:
---------------
- Catalog uses canonical keys; aliases are compatibility only
- Do NOT collapse raw/register/OID namespace with canonical namespace
- Catalog defines exposure capability; profile defines applicability
- Runtime resolves from declared sources; discovery gates by tier

For implementation details, see:
- resolver.py: Tier gating and field resolution
- profiles.py: Profile selection from catalog
- validation.py: Contract enforcement
"""

from __future__ import annotations

from typing import Any

SINGLE_PHASE_CATALOG: dict[str, Any] = {
    "profile_id": "cyberpower_modbus_single_phase",
    "protocol": "modbus",
    "tier_model": {
        "normalized": {
            "description": "Stable canonical fields, enabled by default for MQTT/HA",
            "enabled_by_default": True,
        },
        "extended": {
            "description": "Additional documented fields, opt-in only",
            "enabled_by_default": False,
        },
    },
    "sensors": [
        {
            "key": "hardware_fault",
            "label": "Hardware Fault",
            "source": "modbus",
            "register": 8192,
            "category": "diagnostic",
            "tier": "normalized",
        },
        {
            "key": "utility_frequency_out_of_range",
            "label": "Utility Frequency Out of Range",
            "source": "modbus",
            "register": 8200,
            "category": "diagnostic",
            "tier": "normalized",
        },
        {
            "key": "inverter_off",
            "label": "Inverter Off",
            "source": "modbus",
            "register": 8201,
            "category": "diagnostic",
            "tier": "normalized",
        },
        {
            "key": "battery_not_present",
            "label": "Battery Not Present",
            "source": "modbus",
            "register": 8206,
            "category": "diagnostic",
            "tier": "normalized",
        },
        {
            "key": "on_battery_state",
            "aliases": ["battery_discharging"],
            "label": "On Battery",
            "source": "modbus",
            "register": 8209,
            "category": "core",
            "tier": "normalized",
        },
        {
            "key": "battery_charging",
            "label": "Battery Charging",
            "source": "modbus",
            "register": 8210,
            "category": "diagnostic",
            "tier": "normalized",
        },
        {
            "key": "battery_fully_charged",
            "label": "Battery Fully Charged",
            "source": "modbus",
            "register": 8212,
            "category": "diagnostic",
            "tier": "normalized",
        },
        {
            "key": "buzzer_muted",
            "label": "Buzzer Muted",
            "source": "modbus",
            "register": 8224,
            "category": "diagnostic",
            "tier": "normalized",
        },
        {
            "key": "runtime_low",
            "label": "Runtime Low",
            "source": "modbus",
            "register": 8225,
            "category": "diagnostic",
            "tier": "normalized",
        },
        {
            "key": "no_output",
            "label": "No Output",
            "source": "modbus",
            "register": 8226,
            "category": "diagnostic",
            "tier": "normalized",
        },
        {
            "key": "over_temperature",
            "label": "Over Temperature",
            "source": "modbus",
            "register": 8860,
            "category": "diagnostic",
            "tier": "normalized",
        },
        {
            "key": "input_voltage",
            "aliases": ["utility_voltage"],
            "label": "Input Voltage",
            "source": "modbus",
            "register": 12288,
            "unit": "V",
            "category": "core",
            "tier": "normalized",
        },
        {
            "key": "input_frequency",
            "aliases": ["utility_frequency"],
            "label": "Input Frequency",
            "source": "modbus",
            "register": 12289,
            "unit": "Hz",
            "category": "core",
            "tier": "normalized",
        },
        {
            "key": "output_voltage",
            "label": "Output Voltage",
            "source": "modbus",
            "register": 12320,
            "unit": "V",
            "category": "core",
            "tier": "normalized",
        },
        {
            "key": "output_load_percent",
            "aliases": ["load_percent"],
            "label": "Output Load",
            "source": "modbus",
            "register": 12327,
            "unit": "%",
            "category": "core",
            "tier": "normalized",
        },
        {
            "key": "battery_state_of_charge",
            "aliases": ["battery_capacity"],
            "label": "Battery State of Charge",
            "source": "modbus",
            "register": 12418,
            "unit": "%",
            "category": "core",
            "tier": "normalized",
        },
        {
            "key": "runtime_remaining",
            "label": "Runtime Remaining",
            "source": "modbus",
            "register": 12419,
            "unit": "min",
            "category": "core",
            "tier": "normalized",
        },
        {
            "key": "battery_threshold",
            "label": "Battery Threshold",
            "source": "modbus",
            "register": 12435,
            "unit": "%",
            "category": "config",
            "tier": "normalized",
        },
        {
            "key": "runtime_threshold",
            "label": "Runtime Threshold",
            "source": "modbus",
            "register": 12436,
            "unit": "s",
            "category": "config",
            "tier": "normalized",
        },
        {
            "key": "model",
            "label": "Model",
            "source": "snmp",
            "oid": "1.3.6.1.4.1.3808.1.1.1.1.1.1.0",
            "category": "metadata",
            "tier": "normalized",
        },
        {
            "key": "serial_number",
            "label": "Serial Number",
            "source": "snmp",
            "oid": "1.3.6.1.4.1.3808.1.1.1.1.2.3.0",
            "category": "metadata",
            "tier": "normalized",
        },
        {
            "key": "sw_version",
            "label": "Software Version",
            "source": "snmp",
            "oid": "1.3.6.1.4.1.3808.1.1.1.1.2.4.0",
            "category": "metadata",
            "tier": "normalized",
        },
        {
            "key": "card_model",
            "label": "Card Model",
            "source": "snmp",
            "oid": "1.3.6.1.4.1.3808.1.1.1.1.1.2.0",
            "category": "metadata",
            "tier": "extended",
        },
        {
            "key": "ups_firmware",
            "label": "UPS Firmware Version",
            "source": "snmp",
            "oid": "1.3.6.1.4.1.3808.1.1.1.1.2.1.0",
            "category": "metadata",
            "tier": "extended",
        },
        {
            "key": "battery_replace_date_snmp",
            "label": "Battery Replace Date (SNMP)",
            "source": "snmp",
            "oid": "1.3.6.1.4.1.3808.1.1.1.2.1.3.0",
            "category": "metadata",
            "tier": "extended",
        },
    ],
}

# Three-Phase Catalog
# Source: legacy registers_three_phase.py sensor descriptions

THREE_PHASE_CATALOG: dict[str, Any] = {
    "profile_id": "cyberpower_modbus_three_phase",
    "protocol": "modbus",
    "tier_model": {
        "normalized": {
            "description": "Stable canonical fields, enabled by default for MQTT/HA",
            "enabled_by_default": True,
        },
        "extended": {
            "description": "Additional documented fields, opt-in only",
            "enabled_by_default": False,
        },
    },
    "sensors": [
        # Bypass measurements (normalized - core operational metrics)
        {
            "key": "bypass_voltage_phase_a",
            "label": "Bypass Voltage Phase A",
            "source": "modbus",
            "register": 0x0001,
            "unit": "V",
            "category": "core",
            "tier": "normalized",
        },
        {
            "key": "bypass_voltage_phase_b",
            "label": "Bypass Voltage Phase B",
            "source": "modbus",
            "register": 0x0002,
            "unit": "V",
            "category": "core",
            "tier": "normalized",
        },
        {
            "key": "bypass_voltage_phase_c",
            "label": "Bypass Voltage Phase C",
            "source": "modbus",
            "register": 0x0003,
            "unit": "V",
            "category": "core",
            "tier": "normalized",
        },
        # Input measurements (normalized - core operational metrics)
        {
            "key": "input_voltage_phase_a",
            "label": "Input Voltage Phase A",
            "source": "modbus",
            "register": 0x000D,
            "unit": "V",
            "category": "core",
            "tier": "normalized",
        },
        {
            "key": "input_voltage_phase_b",
            "label": "Input Voltage Phase B",
            "source": "modbus",
            "register": 0x000E,
            "unit": "V",
            "category": "core",
            "tier": "normalized",
        },
        {
            "key": "input_voltage_phase_c",
            "label": "Input Voltage Phase C",
            "source": "modbus",
            "register": 0x000F,
            "unit": "V",
            "category": "core",
            "tier": "normalized",
        },
        # Output measurements (normalized - core operational metrics)
        {
            "key": "output_voltage_phase_a",
            "label": "Output Voltage Phase A",
            "source": "modbus",
            "register": 0x0019,
            "unit": "V",
            "category": "core",
            "tier": "normalized",
        },
        {
            "key": "output_voltage_phase_b",
            "label": "Output Voltage Phase B",
            "source": "modbus",
            "register": 0x001A,
            "unit": "V",
            "category": "core",
            "tier": "normalized",
        },
        {
            "key": "output_voltage_phase_c",
            "label": "Output Voltage Phase C",
            "source": "modbus",
            "register": 0x001B,
            "unit": "V",
            "category": "core",
            "tier": "normalized",
        },
        {
            "key": "output_current_phase_a",
            "label": "Output Current Phase A",
            "source": "modbus",
            "register": 0x001C,
            "unit": "A",
            "category": "core",
            "tier": "normalized",
        },
        {
            "key": "output_current_phase_b",
            "label": "Output Current Phase B",
            "source": "modbus",
            "register": 0x001D,
            "unit": "A",
            "category": "core",
            "tier": "normalized",
        },
        {
            "key": "output_current_phase_c",
            "label": "Output Current Phase C",
            "source": "modbus",
            "register": 0x001E,
            "unit": "A",
            "category": "core",
            "tier": "normalized",
        },
        {
            "key": "output_active_power_phase_a",
            "label": "Output Active Power Phase A",
            "source": "modbus",
            "register": 0x0028,
            "unit": "kW",
            "category": "core",
            "tier": "normalized",
        },
        {
            "key": "output_active_power_phase_b",
            "label": "Output Active Power Phase B",
            "source": "modbus",
            "register": 0x0029,
            "unit": "kW",
            "category": "core",
            "tier": "normalized",
        },
        {
            "key": "output_active_power_phase_c",
            "label": "Output Active Power Phase C",
            "source": "modbus",
            "register": 0x002A,
            "unit": "kW",
            "category": "core",
            "tier": "normalized",
        },
        {
            "key": "load_percent_phase_a",
            "label": "Load Percent Phase A",
            "source": "modbus",
            "register": 0x002E,
            "unit": "%",
            "category": "core",
            "tier": "normalized",
        },
        {
            "key": "load_percent_phase_b",
            "label": "Load Percent Phase B",
            "source": "modbus",
            "register": 0x002F,
            "unit": "%",
            "category": "core",
            "tier": "normalized",
        },
        {
            "key": "load_percent_phase_c",
            "label": "Load Percent Phase C",
            "source": "modbus",
            "register": 0x0030,
            "unit": "%",
            "category": "core",
            "tier": "normalized",
        },
        # Battery measurements (normalized - core operational metrics)
        {
            "key": "battery_voltage",
            "label": "Battery Voltage",
            "source": "modbus",
            "register": 0x0032,
            "unit": "V",
            "category": "core",
            "tier": "normalized",
        },
        {
            "key": "battery_current",
            "label": "Battery Current",
            "source": "modbus",
            "register": 0x0034,
            "unit": "A",
            "category": "core",
            "tier": "normalized",
        },
        {
            "key": "battery_temperature",
            "label": "Battery Temperature",
            "source": "modbus",
            "register": 0x0036,
            "unit": "°C",
            "category": "core",
            "tier": "normalized",
        },
        {
            "key": "battery_runtime_remaining",
            "label": "Battery Runtime Remaining",
            "source": "modbus",
            "register": 0x0037,
            "unit": "min",
            "category": "core",
            "tier": "normalized",
        },
        {
            "key": "battery_capacity",
            "label": "Battery Capacity",
            "source": "modbus",
            "register": 0x0038,
            "unit": "%",
            "category": "core",
            "tier": "normalized",
        },
        # Status fields (normalized - exposed in legacy sensors)
        {
            "key": "load_on_source",
            "label": "Load On Source",
            "source": "modbus",
            "register": 0x0051,
            "category": "diagnostic",
            "tier": "normalized",
        },
        {
            "key": "battery_status",
            "label": "Battery Status",
            "source": "modbus",
            "register": 0x0052,
            "category": "diagnostic",
            "tier": "normalized",
        },
        {
            "key": "battery_test_result",
            "label": "Battery Test Result",
            "source": "modbus",
            "register": 0x0063,
            "category": "diagnostic",
            "tier": "normalized",
        },
        {
            "key": "battery_maintain_result",
            "label": "Battery Maintain Result",
            "source": "modbus",
            "register": 0x0065,
            "category": "diagnostic",
            "tier": "normalized",
        },
        # Binary sensors (normalized - exposed in legacy binary_sensors)
        {
            "key": "battery_connected",
            "label": "Battery Connected",
            "source": "modbus",
            "register": 0x0053,
            "category": "diagnostic",
            "tier": "normalized",
        },
        {
            "key": "epo_active",
            "label": "EPO Active",
            "source": "modbus",
            "register": 0x0055,
            "category": "diagnostic",
            "tier": "normalized",
        },
        {
            "key": "inverter_capacity_low",
            "label": "Inverter Capacity Low",
            "source": "modbus",
            "register": 0x0056,
            "category": "diagnostic",
            "tier": "normalized",
        },
        {
            "key": "input_fail",
            "label": "Input Fail",
            "source": "modbus",
            "register": 0x0058,
            "category": "diagnostic",
            "tier": "normalized",
        },
        {
            "key": "bypass_sequence_fail",
            "label": "Bypass Sequence Fail",
            "source": "modbus",
            "register": 0x0059,
            "category": "diagnostic",
            "tier": "normalized",
        },
        {
            "key": "bypass_voltage_fail",
            "label": "Bypass Voltage Fail",
            "source": "modbus",
            "register": 0x005A,
            "category": "diagnostic",
            "tier": "normalized",
        },
        {
            "key": "bypass_fail",
            "label": "Bypass Fail",
            "source": "modbus",
            "register": 0x005B,
            "category": "diagnostic",
            "tier": "normalized",
        },
        {
            "key": "bypass_overload",
            "label": "Bypass Overload",
            "source": "modbus",
            "register": 0x005C,
            "category": "diagnostic",
            "tier": "normalized",
        },
        {
            "key": "bypass_overload_timeout",
            "label": "Bypass Overload Timeout",
            "source": "modbus",
            "register": 0x005D,
            "category": "diagnostic",
            "tier": "normalized",
        },
        {
            "key": "bypass_untrack",
            "label": "Bypass Untrack",
            "source": "modbus",
            "register": 0x005E,
            "category": "diagnostic",
            "tier": "normalized",
        },
        {
            "key": "output_shorted",
            "label": "Output Shorted",
            "source": "modbus",
            "register": 0x0060,
            "category": "diagnostic",
            "tier": "normalized",
        },
        {
            "key": "battery_eod",
            "label": "Battery End of Discharge",
            "source": "modbus",
            "register": 0x0061,
            "category": "diagnostic",
            "tier": "normalized",
        },
        {
            "key": "manual_bypass",
            "label": "Manual Bypass",
            "source": "modbus",
            "register": 0x006A,
            "category": "diagnostic",
            "tier": "normalized",
        },
        {
            "key": "battery_volt_low",
            "label": "Battery Voltage Low",
            "source": "modbus",
            "register": 0x006B,
            "category": "diagnostic",
            "tier": "normalized",
        },
        {
            "key": "lost_redundant",
            "label": "Lost Redundancy",
            "source": "modbus",
            "register": 0x0070,
            "category": "diagnostic",
            "tier": "normalized",
        },
        # Extended tier - additional measurements not in legacy sensor list
        {
            "key": "bypass_current_phase_a",
            "label": "Bypass Current Phase A",
            "source": "modbus",
            "register": 0x0004,
            "unit": "A",
            "category": "extended",
            "tier": "extended",
        },
        {
            "key": "bypass_current_phase_b",
            "label": "Bypass Current Phase B",
            "source": "modbus",
            "register": 0x0005,
            "unit": "A",
            "category": "extended",
            "tier": "extended",
        },
        {
            "key": "bypass_current_phase_c",
            "label": "Bypass Current Phase C",
            "source": "modbus",
            "register": 0x0006,
            "unit": "A",
            "category": "extended",
            "tier": "extended",
        },
        {
            "key": "bypass_frequency_phase_a",
            "label": "Bypass Frequency Phase A",
            "source": "modbus",
            "register": 0x0007,
            "unit": "Hz",
            "category": "extended",
            "tier": "extended",
        },
        {
            "key": "bypass_frequency_phase_b",
            "label": "Bypass Frequency Phase B",
            "source": "modbus",
            "register": 0x0008,
            "unit": "Hz",
            "category": "extended",
            "tier": "extended",
        },
        {
            "key": "bypass_frequency_phase_c",
            "label": "Bypass Frequency Phase C",
            "source": "modbus",
            "register": 0x0009,
            "unit": "Hz",
            "category": "extended",
            "tier": "extended",
        },
        {
            "key": "bypass_pf_phase_a",
            "label": "Bypass Power Factor Phase A",
            "source": "modbus",
            "register": 0x000A,
            "unit": "pf",
            "category": "extended",
            "tier": "extended",
        },
        {
            "key": "bypass_pf_phase_b",
            "label": "Bypass Power Factor Phase B",
            "source": "modbus",
            "register": 0x000B,
            "unit": "pf",
            "category": "extended",
            "tier": "extended",
        },
        {
            "key": "bypass_pf_phase_c",
            "label": "Bypass Power Factor Phase C",
            "source": "modbus",
            "register": 0x000C,
            "unit": "pf",
            "category": "extended",
            "tier": "extended",
        },
        {
            "key": "input_current_phase_a",
            "label": "Input Current Phase A",
            "source": "modbus",
            "register": 0x0010,
            "unit": "A",
            "category": "extended",
            "tier": "extended",
        },
        {
            "key": "input_current_phase_b",
            "label": "Input Current Phase B",
            "source": "modbus",
            "register": 0x0011,
            "unit": "A",
            "category": "extended",
            "tier": "extended",
        },
        {
            "key": "input_current_phase_c",
            "label": "Input Current Phase C",
            "source": "modbus",
            "register": 0x0012,
            "unit": "A",
            "category": "extended",
            "tier": "extended",
        },
        {
            "key": "input_frequency_phase_a",
            "label": "Input Frequency Phase A",
            "source": "modbus",
            "register": 0x0013,
            "unit": "Hz",
            "category": "extended",
            "tier": "extended",
        },
        {
            "key": "input_frequency_phase_b",
            "label": "Input Frequency Phase B",
            "source": "modbus",
            "register": 0x0014,
            "unit": "Hz",
            "category": "extended",
            "tier": "extended",
        },
        {
            "key": "input_frequency_phase_c",
            "label": "Input Frequency Phase C",
            "source": "modbus",
            "register": 0x0015,
            "unit": "Hz",
            "category": "extended",
            "tier": "extended",
        },
        {
            "key": "input_pf_phase_a",
            "label": "Input Power Factor Phase A",
            "source": "modbus",
            "register": 0x0016,
            "unit": "pf",
            "category": "extended",
            "tier": "extended",
        },
        {
            "key": "input_pf_phase_b",
            "label": "Input Power Factor Phase B",
            "source": "modbus",
            "register": 0x0017,
            "unit": "pf",
            "category": "extended",
            "tier": "extended",
        },
        {
            "key": "input_pf_phase_c",
            "label": "Input Power Factor Phase C",
            "source": "modbus",
            "register": 0x0018,
            "unit": "pf",
            "category": "extended",
            "tier": "extended",
        },
        {
            "key": "output_frequency_phase_a",
            "label": "Output Frequency Phase A",
            "source": "modbus",
            "register": 0x001F,
            "unit": "Hz",
            "category": "extended",
            "tier": "extended",
        },
        {
            "key": "output_frequency_phase_b",
            "label": "Output Frequency Phase B",
            "source": "modbus",
            "register": 0x0020,
            "unit": "Hz",
            "category": "extended",
            "tier": "extended",
        },
        {
            "key": "output_frequency_phase_c",
            "label": "Output Frequency Phase C",
            "source": "modbus",
            "register": 0x0021,
            "unit": "Hz",
            "category": "extended",
            "tier": "extended",
        },
        {
            "key": "output_pf_phase_a",
            "label": "Output Power Factor Phase A",
            "source": "modbus",
            "register": 0x0022,
            "unit": "pf",
            "category": "extended",
            "tier": "extended",
        },
        {
            "key": "output_pf_phase_b",
            "label": "Output Power Factor Phase B",
            "source": "modbus",
            "register": 0x0023,
            "unit": "pf",
            "category": "extended",
            "tier": "extended",
        },
        {
            "key": "output_pf_phase_c",
            "label": "Output Power Factor Phase C",
            "source": "modbus",
            "register": 0x0024,
            "unit": "pf",
            "category": "extended",
            "tier": "extended",
        },
        {
            "key": "output_apparent_power_phase_a",
            "label": "Output Apparent Power Phase A",
            "source": "modbus",
            "register": 0x0025,
            "unit": "VA",
            "category": "extended",
            "tier": "extended",
        },
        {
            "key": "output_apparent_power_phase_b",
            "label": "Output Apparent Power Phase B",
            "source": "modbus",
            "register": 0x0026,
            "unit": "VA",
            "category": "extended",
            "tier": "extended",
        },
        {
            "key": "output_apparent_power_phase_c",
            "label": "Output Apparent Power Phase C",
            "source": "modbus",
            "register": 0x0027,
            "unit": "VA",
            "category": "extended",
            "tier": "extended",
        },
        {
            "key": "output_reactive_power_phase_a",
            "label": "Output Reactive Power Phase A",
            "source": "modbus",
            "register": 0x002B,
            "unit": "VAR",
            "category": "extended",
            "tier": "extended",
        },
        {
            "key": "output_reactive_power_phase_b",
            "label": "Output Reactive Power Phase B",
            "source": "modbus",
            "register": 0x002C,
            "unit": "VAR",
            "category": "extended",
            "tier": "extended",
        },
        {
            "key": "output_reactive_power_phase_c",
            "label": "Output Reactive Power Phase C",
            "source": "modbus",
            "register": 0x002D,
            "unit": "VAR",
            "category": "extended",
            "tier": "extended",
        },
        {
            "key": "environment_temperature",
            "label": "Environment Temperature",
            "source": "modbus",
            "register": 0x0031,
            "unit": "°C",
            "category": "extended",
            "tier": "extended",
        },
    ],
}
