# SPDX-FileCopyrightText: 2026 github.com/aburow
# SPDX-License-Identifier: GPL-3.0-only

from __future__ import annotations

from typing import Any

REGISTERS_SINGLE_PHASE: list[dict[str, Any]] = [
    {
        "key": "hardware_fault",
        "address": 8192,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "utility_frequency_out_of_range",
        "address": 8200,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {"key": "inverter_off", "address": 8201, "count": 1, "type": "uint16", "scale": 1},
    {
        "key": "battery_not_present",
        "address": 8206,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "battery_discharging",
        "address": 8209,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "battery_charging",
        "address": 8210,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "battery_fully_charged",
        "address": 8212,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {"key": "buzzer_muted", "address": 8224, "count": 1, "type": "uint16", "scale": 1},
    {"key": "runtime_low", "address": 8225, "count": 1, "type": "uint16", "scale": 1},
    {"key": "no_output", "address": 8226, "count": 1, "type": "uint16", "scale": 1},
    {
        "key": "over_temperature",
        "address": 8860,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "utility_voltage",
        "address": 12288,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "utility_frequency",
        "address": 12289,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "output_voltage",
        "address": 12320,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "output_load_percent",
        "address": 12327,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "battery_capacity",
        "address": 12418,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "runtime_remaining",
        "address": 12419,
        "count": 2,
        "type": "uint32",
        "scale": 10,
        "word_order": "little",
    },
    {
        "key": "battery_threshold",
        "address": 12435,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "runtime_threshold",
        "address": 12436,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
]

REGISTER_BLOCKS_SINGLE_PHASE: list[dict[str, Any]] = [
    {
        "name": "status",
        "start_address": 8192,
        "count": 35,
        "registers": [8192, 8200, 8201, 8206, 8209, 8210, 8212, 8224, 8225, 8226],
    },
    {
        "name": "temperature_fault",
        "start_address": 8860,
        "count": 1,
        "registers": [8860],
    },
    {
        "name": "measurements_primary",
        "start_address": 12288,
        "count": 40,
        "registers": [12288, 12289, 12320, 12327],
    },
    {
        "name": "measurements_battery",
        "start_address": 12418,
        "count": 19,
        "registers": [12418, 12419, 12435, 12436],
    },
]

# Three-Phase Register Definitions
# Source: legacy registers_three_phase.py

REGISTERS_THREE_PHASE: list[dict[str, Any]] = [
    # Bypass measurements (Phase A, B, C)
    {
        "key": "bypass_voltage_phase_a",
        "address": 0x0001,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "bypass_voltage_phase_b",
        "address": 0x0002,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "bypass_voltage_phase_c",
        "address": 0x0003,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "bypass_current_phase_a",
        "address": 0x0004,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "bypass_current_phase_b",
        "address": 0x0005,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "bypass_current_phase_c",
        "address": 0x0006,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "bypass_frequency_phase_a",
        "address": 0x0007,
        "count": 1,
        "type": "uint16",
        "scale": 100,
    },
    {
        "key": "bypass_frequency_phase_b",
        "address": 0x0008,
        "count": 1,
        "type": "uint16",
        "scale": 100,
    },
    {
        "key": "bypass_frequency_phase_c",
        "address": 0x0009,
        "count": 1,
        "type": "uint16",
        "scale": 100,
    },
    {
        "key": "bypass_pf_phase_a",
        "address": 0x000A,
        "count": 1,
        "type": "uint16",
        "scale": 100,
    },
    {
        "key": "bypass_pf_phase_b",
        "address": 0x000B,
        "count": 1,
        "type": "uint16",
        "scale": 100,
    },
    {
        "key": "bypass_pf_phase_c",
        "address": 0x000C,
        "count": 1,
        "type": "uint16",
        "scale": 100,
    },
    # Input measurements (Phase A, B, C)
    {
        "key": "input_voltage_phase_a",
        "address": 0x000D,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "input_voltage_phase_b",
        "address": 0x000E,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "input_voltage_phase_c",
        "address": 0x000F,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "input_current_phase_a",
        "address": 0x0010,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "input_current_phase_b",
        "address": 0x0011,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "input_current_phase_c",
        "address": 0x0012,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "input_frequency_phase_a",
        "address": 0x0013,
        "count": 1,
        "type": "uint16",
        "scale": 100,
    },
    {
        "key": "input_frequency_phase_b",
        "address": 0x0014,
        "count": 1,
        "type": "uint16",
        "scale": 100,
    },
    {
        "key": "input_frequency_phase_c",
        "address": 0x0015,
        "count": 1,
        "type": "uint16",
        "scale": 100,
    },
    {
        "key": "input_pf_phase_a",
        "address": 0x0016,
        "count": 1,
        "type": "uint16",
        "scale": 100,
    },
    {
        "key": "input_pf_phase_b",
        "address": 0x0017,
        "count": 1,
        "type": "uint16",
        "scale": 100,
    },
    {
        "key": "input_pf_phase_c",
        "address": 0x0018,
        "count": 1,
        "type": "uint16",
        "scale": 100,
    },
    # Output measurements (Phase A, B, C)
    {
        "key": "output_voltage_phase_a",
        "address": 0x0019,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "output_voltage_phase_b",
        "address": 0x001A,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "output_voltage_phase_c",
        "address": 0x001B,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "output_current_phase_a",
        "address": 0x001C,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "output_current_phase_b",
        "address": 0x001D,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "output_current_phase_c",
        "address": 0x001E,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "output_frequency_phase_a",
        "address": 0x001F,
        "count": 1,
        "type": "uint16",
        "scale": 100,
    },
    {
        "key": "output_frequency_phase_b",
        "address": 0x0020,
        "count": 1,
        "type": "uint16",
        "scale": 100,
    },
    {
        "key": "output_frequency_phase_c",
        "address": 0x0021,
        "count": 1,
        "type": "uint16",
        "scale": 100,
    },
    {
        "key": "output_pf_phase_a",
        "address": 0x0022,
        "count": 1,
        "type": "uint16",
        "scale": 100,
    },
    {
        "key": "output_pf_phase_b",
        "address": 0x0023,
        "count": 1,
        "type": "uint16",
        "scale": 100,
    },
    {
        "key": "output_pf_phase_c",
        "address": 0x0024,
        "count": 1,
        "type": "uint16",
        "scale": 100,
    },
    {
        "key": "output_apparent_power_phase_a",
        "address": 0x0025,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "output_apparent_power_phase_b",
        "address": 0x0026,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "output_apparent_power_phase_c",
        "address": 0x0027,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "output_active_power_phase_a",
        "address": 0x0028,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "output_active_power_phase_b",
        "address": 0x0029,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "output_active_power_phase_c",
        "address": 0x002A,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "output_reactive_power_phase_a",
        "address": 0x002B,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "output_reactive_power_phase_b",
        "address": 0x002C,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "output_reactive_power_phase_c",
        "address": 0x002D,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "load_percent_phase_a",
        "address": 0x002E,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "load_percent_phase_b",
        "address": 0x002F,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "load_percent_phase_c",
        "address": 0x0030,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    # Environmental and battery measurements
    {
        "key": "environment_temperature",
        "address": 0x0031,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "battery_voltage",
        "address": 0x0032,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "battery_current",
        "address": 0x0034,
        "count": 1,
        "type": "int16",
        "scale": 10,
    },
    {
        "key": "battery_temperature",
        "address": 0x0036,
        "count": 1,
        "type": "uint16",
        "scale": 10,
    },
    {
        "key": "battery_runtime_remaining",
        "address": 0x0037,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "battery_capacity",
        "address": 0x0038,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    # Status and diagnostic registers
    {
        "key": "load_on_source",
        "address": 0x0051,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "battery_status",
        "address": 0x0052,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "battery_connected",
        "address": 0x0053,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {"key": "epo_active", "address": 0x0055, "count": 1, "type": "uint16", "scale": 1},
    {
        "key": "inverter_capacity_low",
        "address": 0x0056,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {"key": "input_fail", "address": 0x0058, "count": 1, "type": "uint16", "scale": 1},
    {
        "key": "bypass_sequence_fail",
        "address": 0x0059,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "bypass_voltage_fail",
        "address": 0x005A,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {"key": "bypass_fail", "address": 0x005B, "count": 1, "type": "uint16", "scale": 1},
    {
        "key": "bypass_overload",
        "address": 0x005C,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "bypass_overload_timeout",
        "address": 0x005D,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "bypass_untrack",
        "address": 0x005E,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "output_shorted",
        "address": 0x0060,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {"key": "battery_eod", "address": 0x0061, "count": 1, "type": "uint16", "scale": 1},
    {
        "key": "battery_test_result",
        "address": 0x0063,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "battery_maintain_result",
        "address": 0x0065,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "manual_bypass",
        "address": 0x006A,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "battery_volt_low",
        "address": 0x006B,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
    {
        "key": "lost_redundant",
        "address": 0x0070,
        "count": 1,
        "type": "uint16",
        "scale": 1,
    },
]

REGISTER_BLOCKS_THREE_PHASE: list[dict[str, Any]] = [
    {
        "name": "measurements",
        "start_address": 0x0000,
        "count": 0x39,
    },
    {
        "name": "status",
        "start_address": 0x0050,
        "count": 0x27,
    },
]
